services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=chat_app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat_app
    ports:
      - 54321:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data: