services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
      - valkey
    environment:
      - DB_HOST=
      - CACHE_HOST=
      - CACHE_PORT=
      - DB_PORT=
      - DB_USER=
      - DB_PASSWORD=
      - DB_NAME=
      - JWT_SECRET=
    volumes:
      - .:/app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  valkey:
    image: valkey/valkey
    restart: always
    ports:
      - 6379:6379

volumes:
  db_data: